# Generated by Django 3.2.5 on 2021-07-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_customer_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='allergens',
        ),
    ]
